### PR TITLE
Trim the spaces before persisting to a state file

### PR DESCRIPTION
**Pull request by MikeMcMahon**

### CODE REVIEW

**Comment by nathmclean** [comment]
Hi @MikeMcMahon, looks good to me! Before I merge could I just ask that you bump the minor version (so it would become v0.2.0) in the version file and update the ChangeLog to reflect your changes?

**Comment by MikeMcMahon** [comment]
I've updated the README as well, i meant to unwind that commit and can back it out.  We have actually patched all of the afflicted clusters :)

**Comment by nathmclean** [comment]
Thanks, good to know all of the clusters have the fix. If you could update CHANGELOG.md with you v0.2.0 changes then I'll merge this PR.

**Comment by MikeMcMahon** [comment]
consider it done, and let me know if anything else needs touching up !

**Pull request merged**
