### PR TITLE
Trim the spaces on reading from wavefront

### PR DESCRIPTION
**Pull request by ashwin1dd**
WF seems to be adding a lot of newline chars, compared to tfstate which leads to a lot of noise due to no-op changes: i.e. `"(some condition) > 100\n" => "(some condition) > 100"`

Similar vein as #21 

Open to any feedback!

### CODE REVIEW

**Comment by ashwin1dd** [comment]
@nathmclean @louism517 please review.

**Comment by ashwin1dd** [comment]
bump @nathmclean @louism517

**Comment by ashwin1dd** [comment]
bump @nathmclean @louism517

**Comment by nathmclean** [comment]
@ashwin1dd Sorry for the delay. There're some failing tests at the moment (nothing to do with your changes) I just want to get them fixed so I can run the test suite against all PRs. Then I'll get this merged in ASAP. Should be done today/tomorrow

**Comment by ashwin1dd** [comment]
sounds good, thanks @nathmclean!

**Comment by ashwin1dd** [comment]
thanks

**Pull request merged**
